/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.postnov.receivedBookService;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ReceivedBookServiceApp classUnderTest = new ReceivedBookServiceApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
