/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.postnov.emailSender;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        EmailSenderApp classUnderTest = new EmailSenderApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
