/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.postnov.clientService;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ClientServiceApp classUnderTest = new ClientServiceApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
